import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Button } from "@astryxdesign/core/Button";
import * as stylex from "@stylexjs/stylex";
import { Chart } from "@tanstack/charts/react";
import { barY, defineChart } from "@tanstack/charts";
import { scaleBand } from "@tanstack/charts/scales/band";
import { scaleLinear } from "@tanstack/charts/scales/linear";
import { Boxes, ClipboardList, LayoutDashboard, Layers3, LogOut, Package, Plus, Search, Trash2, X, ArrowRight, Printer, Truck, Check, Pencil, Users } from "lucide-react";
import "./styles.css";
if (import.meta.env.DEV) {
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.href = "/virtual:stylex.css";
  document.head.appendChild(link);
  const runtime = "virtual:stylex:runtime";
  void import(/* @vite-ignore */ runtime);
}

type User = { id: number; name: string; email: string; is_admin: number };
type Filament = { id: number; name: string; brand: string; material: string; color: string; notes: string };
type Product = { id: number; name: string; description: string; image_url: string; price: number; filament_ids: number[] };
type Item = { id: number; product_id: number | null; product_name: string; filament_id: number | null; filament_name: string; color: string; quantity: number; unit_price: number };
type Order = { id: number; customer: string; contact: string; notes: string; status: Status; created_at: string; updated_at: string; items: Item[] };
type Status = "new" | "printing" | "printed" | "shipped";
type Data = { needsSetup: boolean; user: User | null; users: User[]; filaments: Filament[]; products: Product[]; orders: Order[] };
type Page = "overview" | "orders" | "products" | "filaments" | "team";
type Dialog = { type: "order"; value?: Order } | { type: "product"; value?: Product } | { type: "filament"; value?: Filament } | { type: "item"; order: Order } | { type: "user" } | null;
const statusNames: Record<Status, string> = { new: "New", printing: "Printing", printed: "Printed", shipped: "Shipped" };
const statusList: Status[] = ["new", "printing", "printed", "shipped"];
const money = (n: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(n);
const date = (s: string) => new Date(s.replace(" ", "T") + (s.includes("Z") ? "" : "Z")).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
const styles = stylex.create({ brand: { letterSpacing: "-0.045em", fontWeight: 800 } });
async function api(path: string, method = "GET", value?: unknown) {
  const res = await fetch("/api" + path, { method, credentials: "same-origin", headers: value instanceof FormData ? undefined : { "Content-Type": "application/json" }, body: value === undefined ? undefined : value instanceof FormData ? value : JSON.stringify(value) });
  const result = await res.json();
  if (!res.ok) throw new Error(result.error || "Request failed");
  return result;
}
function App() {
  const [data, setData] = useState<Data | null>(null);
  const [page, setPage] = useState<Page>("overview");
  const [dialog, setDialog] = useState<Dialog>(null);
  const [selectedOrder, setSelectedOrder] = useState<number | null>(null);
  const [search, setSearch] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const refresh = async () => setData(await api("/bootstrap"));
  useEffect(() => { refresh().catch(e => setError(e.message)); }, []);
  async function action(work: () => Promise<unknown>, close = true) {
    setBusy(true); setError("");
    try { await work(); await refresh(); if (close) setDialog(null); }
    catch (e) { setError(e instanceof Error ? e.message : "Something went wrong"); }
    finally { setBusy(false); }
  }
  if (!data) return <div className="loading">Loading Printroom… {error}</div>;
  if (!data.user) return <Auth setup={data.needsSetup} onDone={refresh} />;
  const active = data.orders.filter(o => o.status !== "shipped");
  const chosen = data.orders.find(o => o.id === selectedOrder) || null;
  const filtered = data.orders.filter(o => `${o.id} ${o.customer} ${o.items.map(i => i.product_name).join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  const tabs: { id: Page; label: string; icon: React.ReactNode }[] = [
    { id: "overview", label: "Overview", icon: <LayoutDashboard size={18} /> },
    { id: "orders", label: "Orders", icon: <ClipboardList size={18} /> },
    { id: "products", label: "Products", icon: <Boxes size={18} /> },
    { id: "filaments", label: "Filaments", icon: <Layers3 size={18} /> },
    ...(data.user.is_admin ? [{ id: "team" as Page, label: "Team", icon: <Users size={18} /> }] : [])
  ];
  return <div className="app">
    <aside className="sidebar">
      <div className="brand"><div className="brand-icon"><Printer size={22} strokeWidth={2.3} /></div><span {...stylex.props(styles.brand)}>printroom<span className="brand-dot">.</span></span></div>
      <div className="workspace-label">WORKSPACE</div>
      <nav>{tabs.map(t => <button key={t.id} className={page === t.id ? "nav active" : "nav"} onClick={() => { setPage(t.id); setSelectedOrder(null); }}>{t.icon}<span>{t.label}</span>{t.id === "orders" && active.length > 0 && <b>{active.length}</b>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="mini-card"><div className="mini-icon"><Package size={18} /></div><strong>Make something good.</strong><p>Your print studio, all in one place.</p></div><div className="profile"><span className="avatar">{data.user.name.slice(0, 1).toUpperCase()}</span><span className="profile-text"><strong>{data.user.name}</strong><small>{data.user.email}</small></span><button title="Sign out" onClick={() => action(() => api("/logout", "POST"), false)}><LogOut size={17} /></button></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <strong>{tabs.find(t => t.id === page)?.label}</strong></div><div className="top-right"><span className="today">{new Date().toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long" })}</span><span className="top-avatar">{data.user.name.slice(0, 1).toUpperCase()}</span></div></header>
      <div className="content">
        {page === "overview" && <><div className="page-heading"><div><span className="eyebrow">YOUR STUDIO AT A GLANCE</span><h1>Good morning, {data.user.name.split(" ")[0]} <span className="wave">✳</span></h1><p>Here’s what’s happening with your prints today.</p></div><Button label="New order" variant="primary" icon={<Plus size={16}/>} onClick={() => setDialog({ type: "order" })} /></div>
          <div className="stat-grid"><Stat icon={<ClipboardList size={20}/>} label="Total orders" value={data.orders.length} sub="All time" tone="violet"/><Stat icon={<Printer size={20}/>} label="In progress" value={active.length} sub="Need your attention" tone="orange"/><Stat icon={<Check size={20}/>} label="Ready to ship" value={data.orders.filter(o => o.status === "printed").length} sub="Printed & waiting" tone="green"/><Stat icon={<Truck size={20}/>} label="Shipped" value={data.orders.filter(o => o.status === "shipped").length} sub="On their way" tone="blue"/></div>
          <div className="overview-grid"><section className="panel"><div className="panel-head"><div><h2>Order activity</h2><p>Orders created over the last 7 days</p></div></div><ActivityChart orders={data.orders}/></section><section className="panel queue-panel"><div className="panel-head"><div><h2>Up next</h2><p>Your active print queue</p></div><button className="text-button" onClick={() => setPage("orders")}>View all <ArrowRight size={14}/></button></div>{active.length ? active.slice(0, 4).map(o => <button className="queue-row" key={o.id} onClick={() => { setPage("orders"); setSelectedOrder(o.id); }}><span className="queue-icon"><Package size={18}/></span><span><strong>#{String(o.id).padStart(4, "0")} · {o.customer}</strong><small>{o.items.length} {o.items.length === 1 ? "item" : "items"} · {date(o.created_at)}</small></span><StatusBadge status={o.status}/></button>) : <Empty small icon={<Printer/>} title="Your queue is clear" text="New orders will show up here."/>}</section></div>
          <section className="panel recent-panel"><div className="panel-head"><div><h2>Recent orders</h2><p>The latest activity in your studio</p></div><button className="text-button" onClick={() => setPage("orders")}>All orders <ArrowRight size={14}/></button></div><OrderTable orders={data.orders.slice(0, 5)} onOpen={id => { setPage("orders"); setSelectedOrder(id); }}/></section>
        </>}
        {page === "orders" && <><div className="page-heading"><div><span className="eyebrow">KEEP THINGS MOVING</span><h1>Orders</h1><p>Track every print from request to delivery.</p></div><Button label="New order" variant="primary" icon={<Plus size={16}/>} onClick={() => setDialog({ type: "order" })}/></div><div className="toolbar"><div className="search"><Search size={18}/><input aria-label="Search orders" placeholder="Search orders or customers…" value={search} onChange={e => setSearch(e.target.value)}/></div><span className="results">{filtered.length} orders</span></div><section className="panel table-panel"><OrderTable orders={filtered} onOpen={setSelectedOrder}/></section></>}
        {page === "products" && <><div className="page-heading"><div><span className="eyebrow">WHAT YOU MAKE</span><h1>Products</h1><p>Your print catalogue and offered colour options.</p></div><Button label="Add product" variant="primary" icon={<Plus size={16}/>} onClick={() => setDialog({ type: "product" })}/></div>{data.products.length ? <div className="product-grid">{data.products.map(p => <article className="product-card" key={p.id}><div className="product-image">{p.image_url ? <img src={p.image_url} alt={p.name}/> : <Boxes size={38} strokeWidth={1.4}/>}</div><div className="product-body"><div className="product-title"><h3>{p.name}</h3><strong>{money(p.price)}</strong></div><p>{p.description || "No description yet"}</p><div className="product-foot"><div className="swatches">{p.filament_ids.map(fid => { const f = data.filaments.find(x => x.id === fid); return f ? <span key={fid} title={f.name} style={{ background: f.color }}/> : null; })}{p.filament_ids.length === 0 && <small>No colours selected</small>}</div><button className="icon-button" title="Edit product" onClick={() => setDialog({ type: "product", value: p })}><Pencil size={16}/></button></div></div></article>)}</div> : <Empty icon={<Boxes/>} title="Build your catalogue" text="Add a product, then choose which filament colours you can offer." action="Add product" onAction={() => setDialog({ type: "product" })}/>}</>}
        {page === "filaments" && <><div className="page-heading"><div><span className="eyebrow">YOUR COLOUR LIBRARY</span><h1>Filaments</h1><p>Keep the materials and shades you own in one place.</p></div><Button label="Add filament" variant="primary" icon={<Plus size={16}/>} onClick={() => setDialog({ type: "filament" })}/></div>{data.filaments.length ? <div className="filament-grid">{data.filaments.map(f => <article className="filament-card" key={f.id}><div className="filament-swatch" style={{ background: f.color }}><div className="filament-ring"/></div><div className="filament-info"><span className="material">{f.material}</span><h3>{f.name}</h3><p>{f.brand || "Unbranded"} · {f.color.toUpperCase()}</p>{f.notes && <small>{f.notes}</small>}</div><button className="icon-button" title="Edit filament" onClick={() => setDialog({ type: "filament", value: f })}><Pencil size={16}/></button></article>)}</div> : <Empty icon={<Layers3/>} title="Start your colour library" text="Add your first spool to make it available for products." action="Add filament" onAction={() => setDialog({ type: "filament" })}/>}</>}
        {page === "team" && <><div className="page-heading"><div><span className="eyebrow">SHARED WORKSPACE</span><h1>Team</h1><p>Everyone here can manage the same orders and catalogue.</p></div><Button label="Add user" variant="primary" icon={<Plus size={16}/>} onClick={() => setDialog({ type: "user" })}/></div><section className="panel team-list">{data.users.map(u => <div className="team-row" key={u.id}><span className="avatar">{u.name.slice(0,1).toUpperCase()}</span><span><strong>{u.name}</strong><small>{u.email}</small></span><span className="team-role">{u.is_admin ? "Owner" : "Member"}</span></div>)}</section></>}
      </div>
    </main>
    {chosen && page === "orders" && <div className="overlay" onMouseDown={e => { if (e.target === e.currentTarget) setSelectedOrder(null); }}><div className="drawer"><div className="drawer-head"><span className="eyebrow">ORDER DETAILS</span><button className="icon-button" onClick={() => setSelectedOrder(null)} aria-label="Close"><X size={20}/></button></div><h2>Order #{String(chosen.id).padStart(4, "0")}</h2><p className="drawer-sub">Created {date(chosen.created_at)}</p><div className="detail-section"><label>STATUS</label><select value={chosen.status} onChange={e => action(() => api("/orders/" + chosen.id, "PUT", { customer: chosen.customer, contact: chosen.contact, notes: chosen.notes, status: e.target.value }), false)}>{statusList.map(s => <option key={s} value={s}>{statusNames[s]}</option>)}</select></div><div className="detail-section"><label>CUSTOMER</label><strong>{chosen.customer}</strong>{chosen.contact && <p>{chosen.contact}</p>}</div><div className="detail-section"><div className="detail-section-title"><label>PRINT ITEMS</label><button className="text-button" onClick={() => setDialog({ type: "item", order: chosen })}><Plus size={15}/> Add item</button></div>{chosen.items.length ? chosen.items.map(i => <div className="item-row" key={i.id}><span className="item-color" style={{ background: i.color }}/><span><strong>{i.product_name}</strong><small>{i.filament_name || "No filament selected"} · Qty {i.quantity}</small></span><b>{money(i.unit_price * i.quantity)}</b><button className="icon-button" title="Remove item" onClick={() => { if (confirm("Remove this item?")) action(() => api("/items/" + i.id, "DELETE"), false); }}><Trash2 size={15}/></button></div>) : <p className="muted">No print items yet. Add one to get started.</p>}<div className="total"><span>Order total</span><strong>{money(chosen.items.reduce((sum, i) => sum + i.unit_price * i.quantity, 0))}</strong></div></div>{chosen.notes && <div className="detail-section"><label>NOTES</label><p>{chosen.notes}</p></div>}<div className="drawer-actions"><button className="outline-button" onClick={() => setDialog({ type: "order", value: chosen })}>Edit details</button><button className="danger-text" onClick={() => { if (confirm("Delete this order and all its items?")) action(async () => { await api("/orders/" + chosen.id, "DELETE"); setSelectedOrder(null); }, false); }}>Delete order</button></div></div></div>}
    {dialog && <div className="overlay modal-overlay" onMouseDown={e => { if (e.target === e.currentTarget) setDialog(null); }}><div className="modal"><div className="modal-top"><div><span className="eyebrow">PRINTROOM</span><h2>{dialog.type === "item" ? "Add print item" : `${"value" in dialog && dialog.value ? "Edit" : "Add"} ${dialog.type}`}</h2></div><button className="icon-button" onClick={() => setDialog(null)} aria-label="Close"><X size={20}/></button></div>{dialog.type === "order" && <OrderForm value={dialog.value} busy={busy} onSubmit={v => action(() => api(dialog.value ? "/orders/" + dialog.value.id : "/orders", dialog.value ? "PUT" : "POST", v))}/>}
      {dialog.type === "filament" && <FilamentForm value={dialog.value} busy={busy} onSubmit={v => action(() => api(dialog.value ? "/filaments/" + dialog.value.id : "/filaments", dialog.value ? "PUT" : "POST", v))} onDelete={dialog.value ? () => { if (confirm("Delete this filament?")) action(() => api("/filaments/" + dialog.value!.id, "DELETE")); } : undefined}/>}
      {dialog.type === "product" && <ProductForm value={dialog.value} filaments={data.filaments} busy={busy} onSubmit={v => action(() => api(dialog.value ? "/products/" + dialog.value.id : "/products", dialog.value ? "PUT" : "POST", v))} onDelete={dialog.value ? () => { if (confirm("Delete this product?")) action(() => api("/products/" + dialog.value!.id, "DELETE")); } : undefined}/>}
      {dialog.type === "item" && <ItemForm products={data.products} filaments={data.filaments} busy={busy} onSubmit={v => action(() => api("/orders/" + dialog.order.id + "/items", "POST", v))}/>}
      {dialog.type === "user" && <UserForm busy={busy} onSubmit={v => action(() => api("/users", "POST", v))}/>}
      {error && <p className="error modal-error">{error}</p>}</div></div>}
    {error && !dialog && <div className="toast" role="alert">{error}<button onClick={() => setError("")}><X size={15}/></button></div>}
  </div>;
}
function Auth({ setup, onDone }: { setup: boolean; onDone: () => Promise<void> }) {
  const [name, setName] = useState(""), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { await api(setup ? "/setup" : "/login", "POST", { name, email, password }); await onDone(); } catch (e) { setError(e instanceof Error ? e.message : "Sign in failed"); } finally { setBusy(false); } }
  return <div className="auth"><div className="auth-art"><div className="auth-brand"><span className="brand-icon"><Printer size={22}/></span><strong>printroom<span className="brand-dot">.</span></strong></div><div className="auth-visual"><span className="orb orb-1"/><span className="orb orb-2"/><span className="orb orb-3"/><div className="visual-card"><Printer size={60} strokeWidth={1.1}/><div className="visual-lines"><i/><i/><i/></div></div></div><div className="auth-copy"><span>YOUR CREATIVE WORKSPACE</span><h1>From idea to<br/>finished print.</h1><p>A calm home for your orders, products and every colour on your shelf.</p></div></div><div className="auth-side"><form className="auth-form" onSubmit={submit}><span className="eyebrow">{setup ? "LET'S GET STARTED" : "WELCOME BACK"}</span><h2>{setup ? "Set up your studio" : "Sign in to Printroom"}</h2><p>{setup ? "Create the first account for your print hub." : "Your print studio is ready when you are."}</p>{setup && <Field label="Your name"><input required value={name} onChange={e => setName(e.target.value)} placeholder="Alex Maker"/></Field>}<Field label="Email address"><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com"/></Field><Field label="Password"><input required type="password" minLength={setup ? 10 : undefined} value={password} onChange={e => setPassword(e.target.value)} placeholder={setup ? "At least 10 characters" : "Your password"}/></Field>{error && <p className="error">{error}</p>}<button className="auth-submit" disabled={busy}>{busy ? "Please wait…" : setup ? "Create studio" : "Sign in"} <ArrowRight size={17}/></button><small className="auth-help">Your session stays signed in on this browser for 30 days.</small></form></div></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Stat({ icon, label, value, sub, tone }: { icon: React.ReactNode; label: string; value: number; sub: string; tone: string }) { return <div className="stat"><div className={`stat-icon ${tone}`}>{icon}</div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>; }
function StatusBadge({ status }: { status: Status }) { return <span className={`status status-${status}`}><i/>{statusNames[status]}</span>; }
function Empty({ icon, title, text, action, onAction, small = false }: { icon: React.ReactNode; title: string; text: string; action?: string; onAction?: () => void; small?: boolean }) { return <div className={small ? "empty small" : "empty"}><span>{icon}</span><h3>{title}</h3><p>{text}</p>{action && <Button label={action} variant="primary" icon={<Plus size={16}/>} onClick={onAction}/>}</div>; }
function OrderTable({ orders, onOpen }: { orders: Order[]; onOpen: (id: number) => void }) { return orders.length ? <div className="table-wrap"><table><thead><tr><th>ORDER</th><th>CUSTOMER</th><th>ITEMS</th><th>DATE</th><th>STATUS</th><th>TOTAL</th><th/></tr></thead><tbody>{orders.map(o => <tr key={o.id} onClick={() => onOpen(o.id)}><td className="order-id">#{String(o.id).padStart(4, "0")}</td><td><strong>{o.customer}</strong></td><td>{o.items.length} {o.items.length === 1 ? "item" : "items"}</td><td>{date(o.created_at)}</td><td><StatusBadge status={o.status}/></td><td className="amount">{money(o.items.reduce((s, i) => s + i.unit_price * i.quantity, 0))}</td><td><ArrowRight size={16}/></td></tr>)}</tbody></table></div> : <Empty small icon={<ClipboardList/>} title="No orders yet" text="Create an order to start tracking your prints."/ >; }
function ActivityChart({ orders }: { orders: Order[] }) {
  const rows = useMemo(() => Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - (6 - i)); const key = d.toISOString().slice(0, 10); return { day: d.toLocaleDateString("en-GB", { weekday: "short" }), count: orders.filter(o => o.created_at.slice(0, 10) === key).length }; }), [orders]);
  const chart = useMemo(() => defineChart({ marks: [barY(rows, { x: "day", y: "count" })], scales: { x: { scale: () => scaleBand().padding(0.55) }, y: { scale: scaleLinear, nice: true, grid: true } } }), [rows]);
  return <div className="chart"><Chart definition={chart} height={205} ariaLabel="Orders created over the last seven days"/></div>;
}
function OrderForm({ value, busy, onSubmit }: { value?: Order; busy: boolean; onSubmit: (v: unknown) => void }) {
  const [customer, setCustomer] = useState(value?.customer || ""), [contact, setContact] = useState(value?.contact || ""), [notes, setNotes] = useState(value?.notes || ""), [status, setStatus] = useState<Status>(value?.status || "new");
  return <form onSubmit={e => { e.preventDefault(); onSubmit({ customer, contact, notes, status }); }}><div className="form-grid"><Field label="Customer name"><input autoFocus required value={customer} onChange={e => setCustomer(e.target.value)} placeholder="e.g. Jamie Smith"/></Field><Field label="Email or contact"><input value={contact} onChange={e => setContact(e.target.value)} placeholder="Optional"/></Field></div>{value && <Field label="Status"><select value={status} onChange={e => setStatus(e.target.value as Status)}>{statusList.map(s => <option key={s} value={s}>{statusNames[s]}</option>)}</select></Field>}<Field label="Notes"><textarea rows={3} value={notes} onChange={e => setNotes(e.target.value)} placeholder="Any requests or delivery details…"/></Field><div className="form-actions"><button className="auth-submit" disabled={busy}>{busy ? "Saving…" : value ? "Save changes" : "Create order"} <ArrowRight size={16}/></button></div></form>;
}
function FilamentForm({ value, busy, onSubmit, onDelete }: { value?: Filament; busy: boolean; onSubmit: (v: unknown) => void; onDelete?: () => void }) {
  const [name, setName] = useState(value?.name || ""), [brand, setBrand] = useState(value?.brand || ""), [material, setMaterial] = useState(value?.material || "PLA"), [color, setColor] = useState(value?.color || "#d48c68"), [notes, setNotes] = useState(value?.notes || "");
  return <form onSubmit={e => { e.preventDefault(); onSubmit({ name, brand, material, color, notes }); }}><div className="form-grid"><Field label="Colour name"><input required autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Terracotta"/></Field><Field label="Brand"><input value={brand} onChange={e => setBrand(e.target.value)} placeholder="e.g. Bambu Lab"/></Field></div><div className="form-grid"><Field label="Material"><select value={material} onChange={e => setMaterial(e.target.value)}>{["PLA", "PETG", "ABS", "ASA", "TPU", "Other"].map(m => <option key={m}>{m}</option>)}</select></Field><Field label="Swatch colour"><div className="color-input"><input type="color" value={color} onChange={e => setColor(e.target.value)}/><span>{color.toUpperCase()}</span></div></Field></div><Field label="Notes"><textarea rows={2} value={notes} onChange={e => setNotes(e.target.value)} placeholder="Finish, spool details…"/></Field><div className="form-actions">{onDelete && <button type="button" className="danger-text" onClick={onDelete}>Delete filament</button>}<button className="auth-submit" disabled={busy}>{busy ? "Saving…" : value ? "Save changes" : "Add filament"} <ArrowRight size={16}/></button></div></form>;
}
function ProductForm({ value, filaments, busy, onSubmit, onDelete }: { value?: Product; filaments: Filament[]; busy: boolean; onSubmit: (v: unknown) => void; onDelete?: () => void }) {
  const [name, setName] = useState(value?.name || ""), [description, setDescription] = useState(value?.description || ""), [price, setPrice] = useState(String(value?.price ?? "")), [imageUrl, setImageUrl] = useState(value?.image_url || ""), [ids, setIds] = useState<number[]>(value?.filament_ids || []), [uploading, setUploading] = useState(false);
  async function upload(file?: File) { if (!file) return; setUploading(true); try { const form = new FormData(); form.append("file", file); const result = await api("/upload", "POST", form); setImageUrl(result.url); } catch (e) { alert(e instanceof Error ? e.message : "Upload failed"); } finally { setUploading(false); } }
  return <form onSubmit={e => { e.preventDefault(); onSubmit({ name, description, price: Number(price || 0), image_url: imageUrl, filament_ids: ids }); }}><div className="form-grid"><Field label="Product name"><input required autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Desk organiser"/></Field><Field label="Price (£)"><input type="number" min="0" step="0.01" value={price} onChange={e => setPrice(e.target.value)} placeholder="0.00"/></Field></div><Field label="Description"><textarea rows={2} value={description} onChange={e => setDescription(e.target.value)} placeholder="A short description of this print…"/></Field><Field label="Example image"><div className="upload-row">{imageUrl && <img src={imageUrl} alt="Product preview"/>}<label className="upload-button">{uploading ? "Uploading…" : imageUrl ? "Change image" : "Upload image"}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => upload(e.target.files?.[0])}/></label><small>PNG, JPEG or WebP · max 5 MB</small></div></Field><div className="field"><span>Offered filaments</span>{filaments.length ? <div className="choice-grid">{filaments.map(f => <label key={f.id} className={ids.includes(f.id) ? "choice selected" : "choice"}><input type="checkbox" checked={ids.includes(f.id)} onChange={e => setIds(e.target.checked ? [...ids, f.id] : ids.filter(x => x !== f.id))}/><i style={{ background: f.color }}/><span>{f.name}</span></label>)}</div> : <p className="muted">Add filaments first to offer colour options.</p>}</div><div className="form-actions">{onDelete && <button type="button" className="danger-text" onClick={onDelete}>Delete product</button>}<button className="auth-submit" disabled={busy || uploading}>{busy ? "Saving…" : value ? "Save changes" : "Add product"} <ArrowRight size={16}/></button></div></form>;
}
function ItemForm({ products, filaments, busy, onSubmit }: { products: Product[]; filaments: Filament[]; busy: boolean; onSubmit: (v: unknown) => void }) {
  const [productId, setProductId] = useState(products[0]?.id || 0), [filamentId, setFilamentId] = useState(0), [quantity, setQuantity] = useState(1);
  const product = products.find(p => p.id === productId), choices = filaments.filter(f => product?.filament_ids.includes(f.id));
  return <form onSubmit={e => { e.preventDefault(); onSubmit({ product_id: productId, filament_id: filamentId || null, quantity }); }}>{products.length ? <><Field label="Product"><select value={productId} onChange={e => { setProductId(Number(e.target.value)); setFilamentId(0); }}>{products.map(p => <option key={p.id} value={p.id}>{p.name} · {money(p.price)}</option>)}</select></Field><div className="form-grid"><Field label="Filament"><select value={filamentId} onChange={e => setFilamentId(Number(e.target.value))}><option value={0}>No filament selected</option>{choices.map(f => <option key={f.id} value={f.id}>{f.name} ({f.material})</option>)}</select></Field><Field label="Quantity"><input type="number" min="1" max="10000" value={quantity} onChange={e => setQuantity(Number(e.target.value))}/></Field></div><div className="form-actions"><button className="auth-submit" disabled={busy}>{busy ? "Adding…" : "Add to order"} <ArrowRight size={16}/></button></div></> : <p className="muted">Add a product to your catalogue before adding print items.</p>}</form>;
}
function UserForm({ busy, onSubmit }: { busy: boolean; onSubmit: (v: unknown) => void }) {
  const [name, setName] = useState(""), [email, setEmail] = useState(""), [password, setPassword] = useState("");
  return <form onSubmit={e => { e.preventDefault(); onSubmit({ name, email, password }); }}><Field label="Name"><input required autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="Alex Maker"/></Field><Field label="Email address"><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="alex@example.com"/></Field><Field label="Temporary password"><input required type="password" minLength={10} value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 10 characters"/></Field><p className="muted">Share the password with this person so they can sign in.</p><div className="form-actions"><button className="auth-submit" disabled={busy}>{busy ? "Adding…" : "Add user"}<ArrowRight size={16}/></button></div></form>;
}
createRoot(document.getElementById("root")!).render(<App/>);
